### ISSUE TITLE
Release to supermarket

### ISSUE THREAD

**Issue by martinb3** [brianbianco/redisio#179]
We should probably do a release, since our last one was in October 2014, and there's been some bugfixes since then. I'm specifically interested in a release that includes https://github.com/brianbianco/redisio/issues/158.

/CC @brianbianco @zarry

**Comment by zarry** [comment]
That sounds good to me.  I don't mind doing the release if they fixed the Mac bug.  Otherwise I will have to defer to @brianbianco.  Let me do some digging to see if that mac supermarket upload was fixed.

**Comment by brianbianco** [comment]
Feel free to cut a release.  I don't recall what the exact error was on Mac.  I can cut the release if that is preferred.  Is the change log up to date?  Has the version been bumped already? 

I can give Martin access on supermarket to do releases as well just need his supermarket account @martinb3 @zarry

**Comment by zarry** [comment]
This little guy... https://tickets.opscode.com/browse/CHEF-4107 

which amazingly still isn't resolved.

**Comment by brianbianco** [comment]
I think chef stopped using jira and started using github for tracking issues?  It is possible this is resolved just never updated in jira.

**Comment by zarry** [comment]
yup, still an issue lol. 

https://github.com/chef/chef/issues/1660

**Comment by zarry** [comment]
I say we get @martinb3 access to publish and at the same time I will get a unix box spun up and get my chef creds onto it so I can publish in the future as needed.

**Comment by martinb3** [comment]
I'm good with doing the release on my Linux workstation -- I usually use [stove](https://github.com/sethvargo/stove), which is super convenient.

**Comment by martinb3** [comment]
Ping. I'd love to get a new release out, so I can remove Berksfile entries. I'm happy to do it, or if someone else wants to do the release, that's great too. Thanks guys!

**Comment by brianbianco** [comment]
@martinb3 go for it! Just make sure the changelog is up to date as well as the version in the metadata file. Also there is a banner in the readme that needs updating to reflect the latest version. It's right at the top!

**Comment by martinb3** [comment]
@brianbianco I don't appear to be added as a collaborator on Supermarket, so I'm unable to do it right now.

**Comment by brianbianco** [comment]
@martinb3 email me your username. Brian.bianco@gmail.com

**Comment by martinb3** [comment]
I've got access now. Just being sure we've cleaned up all the outstanding issues, and I'll do a release :)
